"""test_m1_m2_generated_and_imports.py — regression for the M1/M2 audit fixes.

M1 (coverage_planner): targets whose SUT the classifier flagged
    `generated/excluded` (OpenAPI/codegen DTOs) are dropped BEFORE scoring, so a
    high-missed-branch autogenerated equals() can no longer dominate the batch
    plan over real business logic.

M2 (test_patch_applier):
    a) _prune_unused_imports removes import lines whose symbol is never used,
       keeps used / annotation-referenced / wildcard imports → no SonarQube
       "Unused imports" violation from the fixed template block.
    b) _render_from_template drops @ExtendWith(MockitoExtension.class)/@InjectMocks
       when there are no @Mock collaborators AND the body never references `sut`
       (static-utility SUTs), but keeps the scaffolding when `sut` is used so the
       SUT is always instantiable.

Run: `python tools/python/tests/test_m1_m2_generated_and_imports.py`
Exits non-zero on any failure.
"""
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from coverage_planner import plan  # noqa: E402
from test_patch_applier import (  # noqa: E402
    _load_template,
    _prune_unused_imports,
    _render_from_template,
)

_TEMPLATES_DIR = HERE.parents[2] / "templates"


def _write(p: Path, obj) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(obj), encoding="utf-8")


# ── M1: planner drops generated/excluded targets ─────────────────────────────

def case_planner_drops_generated_targets() -> None:
    gen_sut = "com.acme.openapi.model.ErrorData"
    real_sut = "com.acme.LogSanitizer"
    with tempfile.TemporaryDirectory() as td:
        state = Path(td)
        _write(state / "coverage-targets.json", {
            "targets": [
                # Autogenerated equals() with many missed branches → high score.
                {"id": "t1", "sut": gen_sut, "method": "equals",
                 "missedLines": 2, "missedBranches": 10},
                # Real logic with a modest score.
                {"id": "t2", "sut": real_sut, "method": "sanitizeForLog",
                 "missedLines": 5, "missedBranches": 0},
            ],
        })
        _write(state / "classification-index.json", {
            "schemaVersion": 1,
            "classes": [
                {"fqcn": gen_sut, "type": "generated/excluded"},
                {"fqcn": real_sut, "type": "util"},
            ],
        })

        result = plan(state, batch_size=10)
        suts = [it["sut"] for it in result["items"]]

        if gen_sut in suts:
            raise AssertionError(
                f"generated/excluded SUT leaked into batch-plan: {suts}"
            )
        if real_sut not in suts:
            raise AssertionError(
                f"real-logic SUT was dropped from batch-plan: {suts}"
            )


def case_planner_keeps_targets_without_classification() -> None:
    # Fallback safety: no classification → no exclusion → behaves as before.
    sut = "com.acme.FooService"
    with tempfile.TemporaryDirectory() as td:
        state = Path(td)
        _write(state / "coverage-targets.json", {
            "targets": [{"id": "t1", "sut": sut, "method": "doX",
                         "missedLines": 4, "missedBranches": 1}],
        })
        result = plan(state, batch_size=10)
        if sut not in [it["sut"] for it in result["items"]]:
            raise AssertionError("target dropped despite no classification present")


# ── M2a: unused-import pruning ────────────────────────────────────────────────

def case_prune_removes_unused_keeps_used_and_wildcard() -> None:
    text = (
        "package com.acme;\n\n"
        "import org.junit.jupiter.api.Test;\n"
        "import static org.mockito.Mockito.when;\n"
        "import static org.assertj.core.api.Assertions.assertThat;\n"
        "import java.util.*;\n\n"
        "class FooTest {\n"
        "    @Test\n"
        "    void shouldX() {\n"
        "        List<String> xs = new ArrayList<>();\n"
        "        assertThat(xs).isEmpty();\n"
        "    }\n"
        "}\n"
    )
    pruned = _prune_unused_imports(text)
    if "Mockito.when" in pruned:
        raise AssertionError("unused 'when' import was not pruned")
    if "Assertions.assertThat" not in pruned:
        raise AssertionError("used 'assertThat' import was wrongly pruned")
    if "api.Test" not in pruned:
        raise AssertionError("annotation-referenced 'Test' import was wrongly pruned")
    if "java.util.*" not in pruned:
        raise AssertionError("wildcard import must always be kept")


def case_prune_ignores_comment_and_string_usage() -> None:
    # The BDD AAA marker `// when` must NOT keep the Mockito `when` import, and a
    # symbol named only inside a string literal is not a real use either.
    text = (
        "package com.acme;\n\n"
        "import static org.mockito.Mockito.when;\n"
        "import static org.assertj.core.api.Assertions.assertThat;\n\n"
        "class FooTest {\n"
        "    @Test\n"
        "    void shouldX() {\n"
        "        // when\n"
        '        String msg = "call when() later";\n'
        "        assertThat(msg).isNotNull();\n"
        "    }\n"
        "}\n"
    )
    pruned = _prune_unused_imports(text)
    if "Mockito.when" in pruned:
        raise AssertionError("`// when` comment / string must NOT keep the unused 'when' import")
    if "Assertions.assertThat" not in pruned:
        raise AssertionError("genuinely used 'assertThat' must be kept")


# ── M2b: conditional Mockito scaffolding ──────────────────────────────────────

def _render(patch: dict) -> str:
    tpl = _load_template("junit5-mockito", _TEMPLATES_DIR)
    return _prune_unused_imports(_render_from_template(tpl, patch))


def case_getter_keeps_scaffold_prunes_extras() -> None:
    out = _render({
        "sut": "com.acme.ClusterStatusDocument",
        "testPackage": "com.acme",
        "fields": [],
        "methods": [{
            "name": "shouldReturnId_whenSet",
            "annotations": ["@Test"],
            "body": 'sut.setId("x");\nassertThat(sut.getId()).isEqualTo("x");',
        }],
    })
    # sut is referenced → Mockito instantiates it → scaffolding stays.
    for needed in ("@InjectMocks", "@ExtendWith(MockitoExtension.class)",
                   "private ClusterStatusDocument sut;"):
        if needed not in out:
            raise AssertionError(f"scaffold dropped for sut-using test: missing {needed!r}")
    # Unused template imports must be gone.
    for gone in ("Mockito.when", "Mockito.verify", "ArgumentMatchers.any",
                 "assertThatThrownBy", "org.mockito.Mock;"):
        if gone in out:
            raise AssertionError(f"unused import survived pruning: {gone!r}")
    if "Assertions.assertThat;" not in out:
        raise AssertionError("used assertThat import was pruned")


def case_static_util_drops_scaffold() -> None:
    out = _render({
        "sut": "com.acme.LogSanitizer",
        "testPackage": "com.acme",
        "fields": [],
        "methods": [{
            "name": "shouldReturnUnknown_whenNull",
            "annotations": ["@Test"],
            "body": 'String r = com.acme.LogSanitizer.sanitizeForLog(null);\n'
                    'assertThat(r).isEqualTo("unknown");',
        }],
    })
    # No mocks and sut never referenced → no Mockito scaffolding at all.
    for gone in ("@ExtendWith(MockitoExtension.class)", "@InjectMocks",
                 "sut;", "org.mockito"):
        if gone in out:
            raise AssertionError(f"Mockito scaffolding/import survived: {gone!r}")
    if "Assertions.assertThat;" not in out:
        raise AssertionError("used assertThat import was pruned")


def case_service_with_mocks_keeps_scaffold() -> None:
    out = _render({
        "sut": "com.acme.FooService",
        "testPackage": "com.acme",
        "fields": [{"name": "repo", "type": "FooRepository", "annotation": "@Mock"}],
        "methods": [{
            "name": "shouldDoX",
            "annotations": ["@Test"],
            "body": "when(repo.find()).thenReturn(null);\nverify(repo).find();",
        }],
    })
    for needed in ("@Mock", "@ExtendWith(MockitoExtension.class)",
                   "Mockito.when", "Mockito.verify"):
        if needed not in out:
            raise AssertionError(f"scaffold/import wrongly removed: missing {needed!r}")
    for gone in ("Mockito.never", "Mockito.times", "assertThatThrownBy"):
        if gone in out:
            raise AssertionError(f"unused import survived pruning: {gone!r}")


# ── runner ────────────────────────────────────────────────────────────────────

def main() -> int:
    cases = [
        ("planner-drops-generated-targets",        case_planner_drops_generated_targets),
        ("planner-keeps-without-classification",    case_planner_keeps_targets_without_classification),
        ("prune-unused-keeps-used-and-wildcard",    case_prune_removes_unused_keeps_used_and_wildcard),
        ("prune-ignores-comment-and-string-usage",  case_prune_ignores_comment_and_string_usage),
        ("getter-keeps-scaffold-prunes-extras",     case_getter_keeps_scaffold_prunes_extras),
        ("static-util-drops-scaffold",              case_static_util_drops_scaffold),
        ("service-with-mocks-keeps-scaffold",       case_service_with_mocks_keeps_scaffold),
    ]
    failed = 0
    for name, fn in cases:
        try:
            fn()
            print(f"OK   {name}")
        except Exception as exc:
            failed += 1
            print(f"FAIL {name}: {exc}")
    if failed:
        print(f"\n{failed} test(s) failed")
        return 1
    print("\nAll M1/M2 cases passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
